spring.application.name=jobScheduled


# Oracle
spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/AUTHPDB1
spring.datasource.username=auth_user1
spring.datasource.password=Auth123456
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# JPA
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# url
region.url=https://provinces.open-api.vn/api/v2


# cron
job.region-sync.cron=0 */2 * * * ?