server.port=8085
server.servlet.context-path=/change-app-service

spring.application.name=change-app-service

# Oracle
spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/AUTHPDB1
spring.datasource.username=change_user1
spring.datasource.password=change@123456
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# JPA
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# OAuth2 Resource Server — validate user JWT
# spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8888/ms-internal-iam/auth/jwks
# ── JWT (verify from auth-service) ──────────────────────────────────────────
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8888/ms-internal-iam/auth

# ── Actuator ─────────────────────────────────────────────────────────────────
management.endpoints.web.exposure.include=health,info

# OAuth2 Client — client_credentials de goi identity-service
spring.security.oauth2.client.registration.iam-service.client-id=change-mgmt-service
spring.security.oauth2.client.registration.iam-service.client-secret=7433458e-85ad-4ee0-b60c-916e09d8eea4
spring.security.oauth2.client.registration.iam-service.authorization-grant-type=client_credentials
spring.security.oauth2.client.registration.iam-service.scope=iam-read
spring.security.oauth2.client.provider.iam-service.token-uri=http://localhost:8888/ms-internal-iam/auth/token

# Identity service
identity.service.uri=http://localhost:8081/iam-identity-service

# CORS
cors.allowed-origins=http://localhost:4201,http://localhost:8085

logging.level.com.iam=DEBUG
logging.level.org.springframework.security=DEBUG
