-- Schema: change_user1 | AUTHPDB1
-- Chay voi user change_user1 sau khi tao Oracle user
-- Khoa ngoai chi la logic view, khong tao constraint

-- ─── Sequences ────────────────────────────────────────────────────────────────

CREATE SEQUENCE SEQ_CHG_CHANGE_REQUEST  START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_CHG_GOLIVE_JOB      START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_CHG_CHECKLIST_ITEM  START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_CHG_TEAM_MEMBER     START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_CHG_APPROVER        START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_CHG_DOCUMENT        START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_CHG_AUDIT_LOG       START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- ─── Tables ───────────────────────────────────────────────────────────────────

CREATE TABLE CHG_CHANGE_REQUEST (
    ID               NUMBER         DEFAULT SEQ_CHG_CHANGE_REQUEST.NEXTVAL PRIMARY KEY,
    CHANGE_ID        VARCHAR2(36)   NOT NULL,
    CHANGE_NAME      VARCHAR2(200)  NOT NULL,
    CONTENT          CLOB,
    GIT_LINK         VARCHAR2(500),
    STATUS           VARCHAR2(20)   NOT NULL,   -- DRAFT/PENDING/APPROVED/EXECUTING/SUCCESS/FAIL
    GOLIVE_AT        TIMESTAMP,
    CREATED_BY       VARCHAR2(100),
    CREATED_BY_CODE  VARCHAR2(50),
    CREATED_AT       TIMESTAMP      DEFAULT SYSTIMESTAMP,
    UPDATED_AT       TIMESTAMP      DEFAULT SYSTIMESTAMP
);

CREATE UNIQUE INDEX UQ_CHG_REQ_CHANGE_ID ON CHG_CHANGE_REQUEST (CHANGE_ID);

CREATE TABLE CHG_GOLIVE_JOB (
    ID                NUMBER         DEFAULT SEQ_CHG_GOLIVE_JOB.NEXTVAL PRIMARY KEY,
    CHANGE_REQUEST_ID NUMBER         NOT NULL,
    NAME              VARCHAR2(200),
    LINK              VARCHAR2(500),
    JOB_TYPE          VARCHAR2(50),              -- MERGE/BUILD/DEPLOY
    ORDER_NUM         NUMBER,
    JOB_STATUS        VARCHAR2(20)   DEFAULT 'PENDING', -- PENDING/RUNNING/SUCCESS/FAIL
    STARTED_AT        TIMESTAMP,
    COMPLETED_AT      TIMESTAMP,
    RESULT_NOTE       VARCHAR2(500),
    STATUS            NUMBER(1)      DEFAULT 1,  -- 1=active, 0=soft deleted
    CREATED_BY        VARCHAR2(100),
    CREATED_BY_CODE   VARCHAR2(50),
    CREATED_AT        TIMESTAMP      DEFAULT SYSTIMESTAMP,
    UPDATED_AT        TIMESTAMP      DEFAULT SYSTIMESTAMP
);

CREATE TABLE CHG_CHECKLIST_ITEM (
    ID                NUMBER         DEFAULT SEQ_CHG_CHECKLIST_ITEM.NEXTVAL PRIMARY KEY,
    CHANGE_REQUEST_ID NUMBER         NOT NULL,
    PHASE             VARCHAR2(20),              -- PRE/DURING/ROLLBACK
    STEP_TEXT         VARCHAR2(1000),
    ORDER_NUM         NUMBER,
    ASSIGNED_TO       VARCHAR2(100),
    ASSIGNED_TO_CODE  VARCHAR2(50),
    TASK_STATUS       VARCHAR2(20)   DEFAULT 'READY',  -- READY/SUCCESS/FAIL
    STATUS            NUMBER(1)      DEFAULT 1,
    CREATED_BY        VARCHAR2(100),
    CREATED_BY_CODE   VARCHAR2(50),
    CREATED_AT        TIMESTAMP      DEFAULT SYSTIMESTAMP,
    UPDATED_AT        TIMESTAMP      DEFAULT SYSTIMESTAMP
);

CREATE TABLE CHG_TEAM_MEMBER (
    ID                NUMBER         DEFAULT SEQ_CHG_TEAM_MEMBER.NEXTVAL PRIMARY KEY,
    CHANGE_REQUEST_ID NUMBER         NOT NULL,
    USER_ID           VARCHAR2(50),
    USERNAME          VARCHAR2(100),
    FULL_NAME         VARCHAR2(200),
    EMPLOYEE_CODE     VARCHAR2(50),
    MEMBER_ROLE       VARCHAR2(20),              -- DEV/TESTER/BA
    IS_LEAD           NUMBER(1)      DEFAULT 0,
    STATUS            NUMBER(1)      DEFAULT 1,
    CREATED_BY        VARCHAR2(100),
    CREATED_BY_CODE   VARCHAR2(50),
    CREATED_AT        TIMESTAMP      DEFAULT SYSTIMESTAMP,
    UPDATED_AT        TIMESTAMP      DEFAULT SYSTIMESTAMP
);

CREATE TABLE CHG_APPROVER (
    ID                NUMBER         DEFAULT SEQ_CHG_APPROVER.NEXTVAL PRIMARY KEY,
    CHANGE_REQUEST_ID NUMBER         NOT NULL,
    USER_ID           VARCHAR2(50),
    USERNAME          VARCHAR2(100),
    FULL_NAME         VARCHAR2(200),
    EMPLOYEE_CODE     VARCHAR2(50),
    APPROVE_STATUS    VARCHAR2(20)   DEFAULT 'PENDING',  -- PENDING/APPROVED/REJECTED
    NOTE              VARCHAR2(1000),
    DECIDED_AT        TIMESTAMP,
    STATUS            NUMBER(1)      DEFAULT 1,
    CREATED_BY        VARCHAR2(100),
    CREATED_BY_CODE   VARCHAR2(50),
    CREATED_AT        TIMESTAMP      DEFAULT SYSTIMESTAMP,
    UPDATED_AT        TIMESTAMP      DEFAULT SYSTIMESTAMP
);

-- ─── New Tables (v2 redesign) ─────────────────────────────────────────────────

CREATE TABLE CHG_DOCUMENT (
    ID                NUMBER         DEFAULT SEQ_CHG_DOCUMENT.NEXTVAL PRIMARY KEY,
    CHANGE_REQUEST_ID NUMBER         NOT NULL,
    DOC_TYPE          VARCHAR2(20)   NOT NULL,   -- GIT/JIRA/CONFLUENCE/BUILD/OTHER
    TITLE             VARCHAR2(200)  NOT NULL,
    URL               VARCHAR2(1000),
    NOTE              VARCHAR2(500),
    STATUS            NUMBER(1)      DEFAULT 1,  -- 1=active, 0=deleted
    CREATED_BY        VARCHAR2(100),
    CREATED_BY_CODE   VARCHAR2(50),
    CREATED_AT        TIMESTAMP      DEFAULT SYSTIMESTAMP,
    UPDATED_AT        TIMESTAMP      DEFAULT SYSTIMESTAMP
);

CREATE TABLE CHG_AUDIT_LOG (
    ID                NUMBER         DEFAULT SEQ_CHG_AUDIT_LOG.NEXTVAL PRIMARY KEY,
    CHANGE_REQUEST_ID NUMBER         NOT NULL,
    ACTION            VARCHAR2(50),   -- CREATED/SUBMITTED/APPROVED/REJECTED/EXECUTED/JOB_RUN/FINALIZED
    FROM_STATUS       VARCHAR2(20),
    TO_STATUS         VARCHAR2(20),
    PERFORMED_BY      VARCHAR2(100),
    PERFORMED_BY_CODE VARCHAR2(50),
    NOTE              VARCHAR2(1000),
    CREATED_AT        TIMESTAMP      DEFAULT SYSTIMESTAMP
);

COMMIT;
