spring.application.name=iam-app-service
server.port=8082

server.servlet.context-path=/iam-app-service

# Oracle
spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/AUTHPDB1
spring.datasource.username=auth_user1
spring.datasource.password=Auth123456
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# JPA
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=redis@123456
spring.data.redis.database=0
spring.data.redis.timeout=5000ms

# ── Kafka ────────────────────────────────────────────────────────────────────
kafka.bootstrap-servers=localhost:19092,localhost:19093,localhost:19094
kafka.sasl.username=kafka_user
kafka.sasl.password=kafka@123456

# ── JWT (verify from auth-service) ──────────────────────────────────────────
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8888/ms-internal-iam/auth

# ── Actuator ─────────────────────────────────────────────────────────────────
management.endpoints.web.exposure.include=health,info

# ── Logging ──────────────────────────────────────────────────────────────────
logging.level.com.iam=DEBUG
logging.level.org.springframework.security=DEBUG
