# Redis - service name in docker network
spring.data.redis.host=redis

# Oracle - connect to host machine from container
spring.datasource.url=jdbc:oracle:thin:@//host.docker.internal:1521/AUTHPDB1

# Kafka - broker names in docker internal network
kafka.bootstrap-servers=kafka-1:9092,kafka-2:9092,kafka-3:9092
