server.port=8080

spring.security.oauth2.resourceserver.jwt.issuer-uri=${AUTH_ISSUER_URI:http://localhost:8888/ms-internal-iam/auth}

gateway.identity-uri=${IDENTITY_URI:http://localhost:8081}
gateway.app-uri=${APP_URI:http://localhost:8082}
gateway.service-token.client-id=${GATEWAY_CLIENT_ID:iam-gateway-user}
gateway.service-token.client-secret=${GATEWAY_CLIENT_SECRET:9917e921-9f81-49c2-a2a7-3bccfcdff11b}
gateway.service-token.token-endpoint=${AUTH_TOKEN_ENDPOINT:http://localhost:8888/ms-internal-iam/auth/token}
gateway.service-token.refresh-buffer-seconds=60

cors.allowed-origin=${CORS_ORIGIN:http://localhost:4200}
