-- =============================================================================
-- IAM Banking System -- Full DDL Script
-- Generated: 2026-06-29
-- Oracle PDB: AUTHPDB1
--
-- HOW TO RUN:
--   sqlplus /nolog @ddl.sql
--
-- SCHEMAS CREATED:
--   auth_user1   -- IAM core schema
--   change_user1 -- Change & Go-Live demo schema
--
-- EXECUTION ORDER:
--   1. Sequences  (no dependencies)
--   2. Tables     (reference sequences via DEFAULT)
--   3. Indexes    (after tables)
--   4. Packages   (reference tables)
-- =============================================================================
WHENEVER SQLERROR EXIT SQL.SQLCODE

-- =============================================================================
-- SCHEMA: auth_user1
-- =============================================================================
CONNECT auth_user1/Auth123456@localhost:1521/AUTHPDB1

-- ------------------------------------------------------------
-- 1. SEQUENCES
-- ------------------------------------------------------------

   CREATE SEQUENCE  "SEQ_AUTH_APPLICATION"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 11 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;


   CREATE SEQUENCE  "SEQ_AUTH_APP_PERMISSION"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 60 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;


   CREATE SEQUENCE  "SEQ_AUTH_CLIENT"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 16 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;


   CREATE SEQUENCE  "SEQ_AUTH_CLIENT_GROUP"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 2 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;


   CREATE SEQUENCE  "SEQ_AUTH_CLIENT_METHOD"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 7 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;


   CREATE SEQUENCE  "SEQ_AUTH_CLIENT_OAUTH"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 17 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;


   CREATE SEQUENCE  "SEQ_AUTH_DEFAULT_APP_PERM"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 63 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;


   CREATE SEQUENCE  "SEQ_AUTH_DEFAULT_RESOURCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 183 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;


   CREATE SEQUENCE  "SEQ_AUTH_DEPARTMENT"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 59 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;


   CREATE SEQUENCE  "SEQ_AUTH_FLOW"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 5 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;


   CREATE SEQUENCE  "SEQ_AUTH_FLOW_EXECUTION"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 7 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;


   CREATE SEQUENCE  "SEQ_AUTH_METHOD"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 4 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;


   CREATE SEQUENCE  "SEQ_AUTH_POSITION"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;


   CREATE SEQUENCE  "SEQ_AUTH_REQUEST_DETAIL"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 53 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;


   CREATE SEQUENCE  "SEQ_AUTH_REQUEST_HEADER"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 37 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;


   CREATE SEQUENCE  "SEQ_AUTH_RESOURCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 25 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;


   CREATE SEQUENCE  "SEQ_AUTH_ROLE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 7 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;


   CREATE SEQUENCE  "SEQ_AUTH_SIGNING_KEY"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 2 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;


   CREATE SEQUENCE  "SEQ_AUTH_THEME"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 2 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;


   CREATE SEQUENCE  "SEQ_AUTH_USER"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 38 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;


   CREATE SEQUENCE  "SEQ_AUTH_USER_ADDRESS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 107 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;


   CREATE SEQUENCE  "SEQ_AUTH_USER_RESOURCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 125 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;


   CREATE SEQUENCE  "SEQ_AUTH_USER_ROLE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 43 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;


   CREATE SEQUENCE  "SEQ_CLIENT_SESSION_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 219 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;


  

-- ------------------------------------------------------------
-- 2. TABLES
-- ------------------------------------------------------------

  CREATE TABLE "AUTH_APPLICATION"
   (	"ID" NUMBER DEFAULT "SEQ_AUTH_APPLICATION"."NEXTVAL" NOT NULL ENABLE,
	"NAME" VARCHAR2(200) NOT NULL ENABLE,
	"DESCRIPTION" VARCHAR2(500),
	"APP_TYPE" VARCHAR2(20) NOT NULL ENABLE,
	"LOGO_URI" VARCHAR2(500),
	"DEFAULT_URL" VARCHAR2(500),
	"STATUS" VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL ENABLE,
	"DEPARTMENT_ID" NUMBER,
	"CREATED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP NOT NULL ENABLE,
	"UPDATED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP NOT NULL ENABLE,
	"GROUP_ID" NUMBER,
	"ACR_LEVEL" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE,
	"THEME_ID" NUMBER DEFAULT 1,
	"SERVICE_CODE" VARCHAR2(100),
	 CONSTRAINT "AUTH_APPLICATION_APP_TYPE_CK" CHECK (APP_TYPE IN ('INTERNAL', 'THIRD_PARTY_LDAP')) ENABLE,
	 CONSTRAINT "AUTH_APPLICATION_STATUS_CK" CHECK (STATUS IN ('ACTIVE', 'INACTIVE')) ENABLE,
	 CONSTRAINT "AUTH_APPLICATION_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE,
	 CONSTRAINT "AUTH_APPLICATION_SERVICE_CODE_UQ" UNIQUE ("SERVICE_CODE")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "AUTH_APP_PERMISSION"
   (	"ID" NUMBER DEFAULT "SEQ_AUTH_APP_PERMISSION"."NEXTVAL" NOT NULL ENABLE,
	"USER_ID" NUMBER NOT NULL ENABLE,
	"APP_ID" NUMBER NOT NULL ENABLE,
	"STATUS" VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL ENABLE,
	"GRANTED_BY" VARCHAR2(100),
	"GRANTED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP NOT NULL ENABLE,
	"EXPIRED_AT" TIMESTAMP (6),
	"REVOKED_BY" VARCHAR2(20),
	"REVOKED_AT" TIMESTAMP (6),
	"GRANT_SOURCE" VARCHAR2(20) DEFAULT 'MANUAL' NOT NULL ENABLE,
	"REQUEST_ID" NUMBER,
	"INACTIVE_FROM_DATE" TIMESTAMP (6),
	"INACTIVE_TO_DATE" TIMESTAMP (6),
	"REASON_REVOKED" VARCHAR2(200),
	 CONSTRAINT "AUTH_APP_PERM_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE,
	 CONSTRAINT "AUTH_APP_PERM_STATUS_CK" CHECK (STATUS IN ('ACTIVE', 'REVOKED', 'EXPIRED', 'SUSPENDED')) ENABLE
   ) ;


  CREATE TABLE "AUTH_CLIENT"
   (	"ID" NUMBER DEFAULT "SEQ_AUTH_CLIENT"."NEXTVAL",
	"CLIENT_ID" VARCHAR2(100) NOT NULL ENABLE,
	"CLIENT_SECRET" VARCHAR2(255),
	"NAME" VARCHAR2(255) NOT NULL ENABLE,
	"CLIENT_TYPE" VARCHAR2(20) NOT NULL ENABLE,
	"ENABLED" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE,
	"CREATED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP NOT NULL ENABLE,
	"UPDATED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP NOT NULL ENABLE,
	"LOGO_URI" VARCHAR2(500),
	"DESCRIPTION" VARCHAR2(500),
	"DEFAULT_URL" VARCHAR2(4000),
	"APP_ID" NUMBER,
	 CONSTRAINT "CK_AUTH_CLIENT_TYPE" CHECK (CLIENT_TYPE IN ('confidential', 'public')) ENABLE,
	 CONSTRAINT "CK_AUTH_CLIENT_ENABLED" CHECK (ENABLED IN (0, 1)) ENABLE,
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE,
	 CONSTRAINT "UQ_AUTH_CLIENT_ID" UNIQUE ("CLIENT_ID")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "AUTH_CLIENT_GROUP"
   (	"ID" NUMBER DEFAULT SEQ_AUTH_CLIENT_GROUP.NEXTVAL,
	"NAME" VARCHAR2(100) NOT NULL ENABLE,
	"CREATED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP NOT NULL ENABLE,
	"UPDATED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP NOT NULL ENABLE,
	"DESCRIPTION" VARCHAR2(4000),
	"STATUS" NUMBER(1,0) DEFAULT 1,
	 CONSTRAINT "PK_AUTH_CLIENT_GROUP" PRIMARY KEY ("ID")
  USING INDEX  ENABLE,
	 CONSTRAINT "UK_AUTH_CLIENT_GROUP_NAME" UNIQUE ("NAME")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "AUTH_CLIENT_METHOD"
   (	"ID" NUMBER DEFAULT "SEQ_AUTH_CLIENT_METHOD"."NEXTVAL",
	"METHOD_ID" NUMBER NOT NULL ENABLE,
	"CONFIG" VARCHAR2(4000),
	"STATUS" VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL ENABLE,
	"CREATED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP NOT NULL ENABLE,
	"UPDATED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP NOT NULL ENABLE,
	"APP_ID" NUMBER,
	 CONSTRAINT "CK_CLIENT_METHOD_STATUS" CHECK (STATUS IN ('ACTIVE', 'INACTIVE')) ENABLE,
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE,
	 CONSTRAINT "UQ_APP_METHOD" UNIQUE ("APP_ID", "METHOD_ID")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "AUTH_CLIENT_OAUTH"
   (	"ID" NUMBER DEFAULT "SEQ_AUTH_CLIENT_OAUTH"."NEXTVAL",
	"CLIENT_ID" NUMBER NOT NULL ENABLE,
	"GRANT_TYPES" VARCHAR2(200) NOT NULL ENABLE,
	"REDIRECT_URIS" VARCHAR2(2000),
	"ALLOWED_SCOPES" VARCHAR2(500) NOT NULL ENABLE,
	"ACCESS_TOKEN_TTL" NUMBER DEFAULT 300 NOT NULL ENABLE,
	"REFRESH_TOKEN_TTL" NUMBER DEFAULT 86400 NOT NULL ENABLE,
	"ID_TOKEN_TTL" NUMBER DEFAULT 3600 NOT NULL ENABLE,
	"TOKEN_ENDPOINT_AUTH" VARCHAR2(50) DEFAULT 'client_secret_basic' NOT NULL ENABLE,
	"REQUIRE_PKCE" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE,
	"REQUIRE_CONSENT" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE,
	"POST_LOGOUT_REDIRECT" VARCHAR2(500),
	"CREATED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP NOT NULL ENABLE,
	"UPDATED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP NOT NULL ENABLE,
	 CONSTRAINT "CK_OAUTH_AUTH_METHOD" CHECK (TOKEN_ENDPOINT_AUTH IN
        ('client_secret_basic', 'client_secret_post', 'none')) ENABLE,
	 CONSTRAINT "CK_OAUTH_PKCE" CHECK (REQUIRE_PKCE IN (0, 1)) ENABLE,
	 CONSTRAINT "CK_OAUTH_CONSENT" CHECK (REQUIRE_CONSENT IN (0, 1)) ENABLE,
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE,
	 UNIQUE ("CLIENT_ID")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "AUTH_CLIENT_SESSION"
   (	"ID" NUMBER DEFAULT "SEQ_CLIENT_SESSION_ID".NEXTVAL NOT NULL ENABLE,
	"USER_SESSION_ID" VARCHAR2(64) NOT NULL ENABLE,
	"APP_ID" NUMBER NOT NULL ENABLE,
	"STATUS" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE,
	"CREATED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP NOT NULL ENABLE,
	"EXPIRES_AT" TIMESTAMP (6) NOT NULL ENABLE,
	 CONSTRAINT "CK_CLIENT_SESSION_STATUS" CHECK (STATUS IN (0, 1)) ENABLE,
	 CONSTRAINT "PK_CLIENT_SESSION" PRIMARY KEY ("ID")
  USING INDEX  ENABLE,
	 CONSTRAINT "UQ_CLIENT_SESSION" UNIQUE ("USER_SESSION_ID", "APP_ID")
  USING INDEX  ENABLE
   )
  PARTITION BY RANGE ("EXPIRES_AT") INTERVAL (NUMTOYMINTERVAL(1, 'MONTH'))
 (PARTITION "P_CLIENT_SESSION_INIT"  VALUES LESS THAN (TIMESTAMP' 2025-01-01 00:00:00') ) ;


  CREATE TABLE "AUTH_DEFAULT_APP_PERMISSION"
   (	"ID" NUMBER DEFAULT "SEQ_AUTH_DEFAULT_APP_PERM"."NEXTVAL" NOT NULL ENABLE,
	"ROLE_ID" VARCHAR2(100) NOT NULL ENABLE,
	"POSITION_CODE" VARCHAR2(100) NOT NULL ENABLE,
	"APPLICATION_ID" NUMBER NOT NULL ENABLE,
	"STATUS" VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL ENABLE,
	"CREATED_BY" VARCHAR2(50) NOT NULL ENABLE,
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
	"UPDATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
	 CONSTRAINT "CK_AUTH_DEFAULT_APP_PERM_STATUS" CHECK (STATUS IN ('ACTIVE', 'INACTIVE')) ENABLE,
	 CONSTRAINT "PK_AUTH_DEFAULT_APP_PERM" PRIMARY KEY ("ID")
  USING INDEX  ENABLE,
	 CONSTRAINT "UQ_AUTH_DEFAULT_APP_PERM" UNIQUE ("ROLE_ID", "POSITION_CODE", "APPLICATION_ID")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "AUTH_DEFAULT_RESOURCE"
   (	"ID" NUMBER DEFAULT "SEQ_AUTH_DEFAULT_RESOURCE"."NEXTVAL" NOT NULL ENABLE,
	"ROLE_ID" NUMBER NOT NULL ENABLE,
	"POSITION_CODE" VARCHAR2(100) NOT NULL ENABLE,
	"RESOURCE_ID" NUMBER NOT NULL ENABLE,
	"ACTIONS" VARCHAR2(200) NOT NULL ENABLE,
	"STATUS" VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL ENABLE,
	"CREATED_BY" VARCHAR2(50) NOT NULL ENABLE,
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
	"UPDATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
	 CONSTRAINT "CK_AUTH_DEFAULT_RESOURCE_STATUS" CHECK (STATUS IN ('ACTIVE', 'INACTIVE')) ENABLE,
	 CONSTRAINT "PK_AUTH_DEFAULT_RESOURCE" PRIMARY KEY ("ID")
  USING INDEX  ENABLE,
	 CONSTRAINT "UQ_AUTH_DEFAULT_RESOURCE" UNIQUE ("ROLE_ID", "POSITION_CODE", "RESOURCE_ID")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "AUTH_DEPARTMENT"
   (	"ID" NUMBER DEFAULT "SEQ_AUTH_DEPARTMENT"."NEXTVAL" NOT NULL ENABLE,
	"CODE" VARCHAR2(50) NOT NULL ENABLE,
	"NAME" VARCHAR2(200) NOT NULL ENABLE,
	"PARENT_ID" NUMBER,
	"CREATED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP NOT NULL ENABLE,
	"STATUS" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE,
	"UPDATED_AT" TIMESTAMP (6),
	 CONSTRAINT "AUTH_DEPARTMENT_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE,
	 CONSTRAINT "AUTH_DEPARTMENT_CODE_UQ" UNIQUE ("CODE")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "AUTH_FLOW"
   (	"ID" NUMBER DEFAULT "SEQ_AUTH_FLOW"."NEXTVAL",
	"ALIAS" VARCHAR2(100) NOT NULL ENABLE,
	"DESCRIPTION" VARCHAR2(500),
	"IS_BUILT_IN" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE,
	"STATUS" VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL ENABLE,
	"CREATED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP NOT NULL ENABLE,
	"UPDATED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP NOT NULL ENABLE,
	"APP_ID" NUMBER NOT NULL ENABLE,
	 CONSTRAINT "CK_AUTH_FLOW_BUILT_IN" CHECK (IS_BUILT_IN IN (0, 1)) ENABLE,
	 CONSTRAINT "CK_AUTH_FLOW_STATUS" CHECK (STATUS IN ('ACTIVE', 'INACTIVE')) ENABLE,
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE,
	 CONSTRAINT "UQ_AUTH_FLOW_APP" UNIQUE ("APP_ID")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "AUTH_FLOW_EXECUTION"
   (	"ID" NUMBER DEFAULT "SEQ_AUTH_FLOW_EXECUTION"."NEXTVAL",
	"FLOW_ID" NUMBER NOT NULL ENABLE,
	"PARENT_NODE_ID" NUMBER,
	"CLIENT_METHOD_ID" NUMBER NOT NULL ENABLE,
	"REQUIREMENT" VARCHAR2(20) NOT NULL ENABLE,
	"IS_DEFAULT" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE,
	"STATUS" VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL ENABLE,
	"CREATED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP NOT NULL ENABLE,
	"UPDATED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP NOT NULL ENABLE,
	 CONSTRAINT "CK_AUTH_EXEC_REQ" CHECK (REQUIREMENT IN ('REQUIRED', 'OPTIONAL', 'ALTERNATIVE', 'DISABLED')) ENABLE,
	 CONSTRAINT "CK_AUTH_EXEC_IS_DEFAULT" CHECK (IS_DEFAULT IN (0, 1)) ENABLE,
	 CONSTRAINT "CK_AUTH_EXEC_STATUS" CHECK (STATUS IN ('ACTIVE', 'INACTIVE')) ENABLE,
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "AUTH_METHOD"
   (	"ID" NUMBER DEFAULT "SEQ_AUTH_METHOD"."NEXTVAL",
	"METHOD" VARCHAR2(100) NOT NULL ENABLE,
	"STATUS" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE,
	"CREATED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP NOT NULL ENABLE,
	"UPDATED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP NOT NULL ENABLE,
	 CONSTRAINT "CK_AUTH_METHOD_STATUS" CHECK (STATUS IN (0, 1)) ENABLE,
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE,
	 CONSTRAINT "UQ_AUTH_METHOD" UNIQUE ("METHOD")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "AUTH_POSITION"
   (	"CODE" VARCHAR2(100) NOT NULL ENABLE,
	"NAME" VARCHAR2(200) NOT NULL ENABLE,
	"DESCRIPTION" VARCHAR2(500),
	"STATUS" VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL ENABLE,
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
	"UPDATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
	 CONSTRAINT "CK_AUTH_POSITION_STATUS" CHECK (STATUS IN ('ACTIVE', 'INACTIVE')) ENABLE,
	 CONSTRAINT "PK_AUTH_POSITION" PRIMARY KEY ("CODE")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "AUTH_PROVINCE"
   (	"CODE" NUMBER NOT NULL ENABLE,
	"NAME" VARCHAR2(200) NOT NULL ENABLE,
	"DIVISION_TYPE" VARCHAR2(50) NOT NULL ENABLE,
	"CODENAME" VARCHAR2(200) NOT NULL ENABLE,
	"PHONE_CODE" NUMBER,
	"STATUS" VARCHAR2(10) DEFAULT 'ACTIVE' NOT NULL ENABLE,
	 CONSTRAINT "CHK_AUTH_PROVINCE_STATUS" CHECK (STATUS IN ('ACTIVE', 'INACTIVE')) ENABLE,
	 CONSTRAINT "PK_AUTH_PROVINCE" PRIMARY KEY ("CODE")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "AUTH_REFRESH_TOKEN"
   (	"TOKEN" VARCHAR2(512) NOT NULL ENABLE,
	"USER_ID" NUMBER(19,0) NOT NULL ENABLE,
	"CLIENT_ID" VARCHAR2(255) NOT NULL ENABLE,
	"APP_ID" NUMBER(19,0) NOT NULL ENABLE,
	"USER_SESSION_ID" VARCHAR2(255) NOT NULL ENABLE,
	"SCOPES" VARCHAR2(1000),
	"STATUS" VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL ENABLE,
	"CREATED_AT" NUMBER(19,0) NOT NULL ENABLE,
	"EXPIRES_AT" NUMBER(19,0) NOT NULL ENABLE,
	 CONSTRAINT "CHK_ART_STATUS" CHECK (STATUS IN ('ACTIVE', 'REVOKED', 'EXPIRED')) ENABLE,
	 CONSTRAINT "PK_AUTH_REFRESH_TOKEN" PRIMARY KEY ("TOKEN")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "AUTH_REQUEST_DETAIL"
   (	"ID" NUMBER DEFAULT "SEQ_AUTH_REQUEST_DETAIL"."NEXTVAL" NOT NULL ENABLE,
	"REQUEST_ID" NUMBER NOT NULL ENABLE,
	"APP_ID" NUMBER,
	"RESOURCE_ID" NUMBER,
	"ACTIONS" VARCHAR2(200),
	"STATUS" VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL ENABLE,
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
	"UPDATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
	 CONSTRAINT "CK_AUTH_REQUEST_DETAIL_STATUS" CHECK (STATUS IN ('ACTIVE','INACTIVE')) ENABLE,
	 CONSTRAINT "PK_AUTH_REQUEST_DETAIL" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "AUTH_REQUEST_HEADER"
   (	"ID" NUMBER DEFAULT "SEQ_AUTH_REQUEST_HEADER"."NEXTVAL" NOT NULL ENABLE,
	"REQUESTED_BY" VARCHAR2(100) NOT NULL ENABLE,
	"REVIEWED_BY" VARCHAR2(100),
	"REASON" VARCHAR2(500) NOT NULL ENABLE,
	"NOTE" VARCHAR2(500),
	"STATUS" VARCHAR2(20) DEFAULT 'DRAFT' NOT NULL ENABLE,
	"REQUESTED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
	"REVIEWED_AT" TIMESTAMP (6),
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
	"UPDATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
	"REQUEST_FOR" VARCHAR2(50) DEFAULT NULL,
	 CONSTRAINT "CK_AUTH_REQUEST_HEADER_STATUS" CHECK (STATUS IN ('DRAFT','OFFICIAL','APPROVED','REJECTED','CANCELLED')) ENABLE,
	 CONSTRAINT "PK_AUTH_REQUEST_HEADER" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "AUTH_RESOURCE"
   (	"ID" NUMBER DEFAULT "SEQ_AUTH_RESOURCE"."NEXTVAL" NOT NULL ENABLE,
	"APP_ID" NUMBER NOT NULL ENABLE,
	"RESOURCE_CODE" VARCHAR2(100) NOT NULL ENABLE,
	"RESOURCE_NAME" VARCHAR2(200) NOT NULL ENABLE,
	"RESOURCE_TYPE" VARCHAR2(50) NOT NULL ENABLE,
	"ACTIONS" VARCHAR2(500) NOT NULL ENABLE,
	"LDAP_GROUP_NAME" VARCHAR2(200),
	"DESCRIPTION" VARCHAR2(500),
	"STATUS" VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL ENABLE,
	"CREATED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP NOT NULL ENABLE,
	 CONSTRAINT "AUTH_RESOURCE_ST_CK" CHECK (STATUS IN ('ACTIVE', 'INACTIVE')) ENABLE,
	 CONSTRAINT "AUTH_RESOURCE_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE,
	 CONSTRAINT "AUTH_RESOURCE_UQ" UNIQUE ("APP_ID", "RESOURCE_CODE")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "AUTH_ROLE"
   (	"ID" NUMBER DEFAULT "SEQ_AUTH_ROLE"."NEXTVAL" NOT NULL ENABLE,
	"CODE" VARCHAR2(50) NOT NULL ENABLE,
	"NAME" VARCHAR2(200) NOT NULL ENABLE,
	"DESCRIPTION" VARCHAR2(500),
	"CREATED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP NOT NULL ENABLE,
	 CONSTRAINT "AUTH_ROLE_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE,
	 CONSTRAINT "AUTH_ROLE_CODE_UQ" UNIQUE ("CODE")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "AUTH_SIGNING_KEY"
   (	"ID" NUMBER DEFAULT "SEQ_AUTH_SIGNING_KEY"."NEXTVAL",
	"KID" VARCHAR2(100) NOT NULL ENABLE,
	"ALGORITHM" VARCHAR2(10) NOT NULL ENABLE,
	"PUBLIC_KEY" CLOB NOT NULL ENABLE,
	"PRIVATE_KEY" CLOB NOT NULL ENABLE,
	"STATUS" VARCHAR2(10) DEFAULT 'ACTIVE' NOT NULL ENABLE,
	"VALID_FROM" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP NOT NULL ENABLE,
	"VALID_UNTIL" TIMESTAMP (6),
	"CREATED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP NOT NULL ENABLE,
	 CONSTRAINT "CK_SIGNING_ALGORITHM" CHECK (ALGORITHM IN ('RS256', 'ES256')) ENABLE,
	 CONSTRAINT "CK_SIGNING_KEY_STATUS" CHECK (STATUS IN ('ACTIVE', 'PASSIVE', 'DISABLED')) ENABLE,
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE,
	 CONSTRAINT "UQ_AUTH_SIGNING_KID" UNIQUE ("KID")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "AUTH_THEME"
   (	"ID" NUMBER DEFAULT "SEQ_AUTH_THEME"."NEXTVAL",
	"NAME" VARCHAR2(255) NOT NULL ENABLE,
	"STATUS" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE,
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSDATE NOT NULL ENABLE,
	"UPDATED_AT" TIMESTAMP (6) DEFAULT SYSDATE NOT NULL ENABLE,
	 CHECK (STATUS IN (0, 1)) ENABLE,
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "AUTH_USER"
   (	"ID" NUMBER DEFAULT "SEQ_AUTH_USER"."NEXTVAL" NOT NULL ENABLE,
	"USERNAME" VARCHAR2(100) NOT NULL ENABLE,
	"EMAIL" VARCHAR2(200) NOT NULL ENABLE,
	"STATUS" VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL ENABLE,
	"MS365_SYNCED" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE,
	"CREATED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP NOT NULL ENABLE,
	"UPDATED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP NOT NULL ENABLE,
	"PASSWORD" VARCHAR2(255),
	"MOBILE" VARCHAR2(20),
	"FORCE_CHANGE_PASSWORD" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE,
	"DISPLAY_NAME" VARCHAR2(200),
	 CONSTRAINT "AUTH_USER_MS365_SYNCED_CK" CHECK (MS365_SYNCED IN (0, 1)) ENABLE,
	 CONSTRAINT "AUTH_USER_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE,
	 CONSTRAINT "AUTH_USER_USERNAME_UQ" UNIQUE ("USERNAME")
  USING INDEX  ENABLE,
	 CONSTRAINT "AUTH_USER_EMAIL_UQ" UNIQUE ("EMAIL")
  USING INDEX  ENABLE,
	 CONSTRAINT "AUTH_USER_STATUS_CK" CHECK (status in ('ACTIVE', 'INACTIVE', 'LOCKED', 'DELETED')) ENABLE
   ) ;


  CREATE TABLE "AUTH_USER_ADDRESS"
   (	"ID" NUMBER DEFAULT SEQ_AUTH_USER_ADDRESS.NEXTVAL NOT NULL ENABLE,
	"USER_ID" NUMBER NOT NULL ENABLE,
	"TYPE" VARCHAR2(10) NOT NULL ENABLE,
	"PROVINCE_CODE" NUMBER,
	"WARD_CODE" NUMBER,
	"DETAIL" VARCHAR2(500),
	"CREATED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP NOT NULL ENABLE,
	"UPDATED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP NOT NULL ENABLE,
	 CONSTRAINT "CHK_AUTH_ADDRESS_TYPE" CHECK (TYPE IN ('PERMANENT', 'TEMPORARY', 'BIRTH')) ENABLE,
	 CONSTRAINT "PK_AUTH_USER_ADDRESS" PRIMARY KEY ("ID")
  USING INDEX  ENABLE,
	 CONSTRAINT "UQ_AUTH_ADDRESS_TYPE" UNIQUE ("USER_ID", "TYPE")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "AUTH_USER_PROFILE"
   (	"USER_ID" NUMBER NOT NULL ENABLE,
	"FIRST_NAME" VARCHAR2(100),
	"LAST_NAME" VARCHAR2(100),
	"FULL_NAME" VARCHAR2(200),
	"DISPLAY_NAME" VARCHAR2(200),
	"GENDER" VARCHAR2(10),
	"DOB" DATE,
	"NATIONALITY" VARCHAR2(100),
	"ETHNIC" VARCHAR2(100),
	"RELIGION" VARCHAR2(100),
	"AVATAR_URL" VARCHAR2(500),
	"CCCD" VARCHAR2(20),
	"CCCD_ISSUED_DATE" DATE,
	"CCCD_ISSUED_PLACE" VARCHAR2(200),
	"EMPLOYEE_CODE" VARCHAR2(50),
	"JOIN_DATE" DATE,
	"DEPARTMENT_ID" NUMBER,
	"POSITION" VARCHAR2(200),
	"CREATED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP NOT NULL ENABLE,
	"UPDATED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP NOT NULL ENABLE,
	"EMAIL_PERSONAL" VARCHAR2(100),
	 CONSTRAINT "CHK_AUTH_PROFILE_GENDER" CHECK (GENDER IN ('MALE', 'FEMALE', 'OTHER')) ENABLE,
	 CONSTRAINT "PK_AUTH_USER_PROFILE" PRIMARY KEY ("USER_ID")
  USING INDEX  ENABLE,
	 CONSTRAINT "UQ_AUTH_PROFILE_EMP_CODE" UNIQUE ("EMPLOYEE_CODE")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "AUTH_USER_RESOURCE"
   (	"ID" NUMBER DEFAULT "SEQ_AUTH_USER_RESOURCE"."NEXTVAL" NOT NULL ENABLE,
	"USER_ID" NUMBER NOT NULL ENABLE,
	"RESOURCE_ID" NUMBER NOT NULL ENABLE,
	"ACTION" VARCHAR2(500) NOT NULL ENABLE,
	"STATUS" VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL ENABLE,
	"GRANTED_BY" VARCHAR2(100),
	"GRANTED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP NOT NULL ENABLE,
	"EXPIRED_AT" TIMESTAMP (6),
	"REVOKED_BY" VARCHAR2(100),
	"REVOKED_AT" TIMESTAMP (6),
	"REQUEST_ID" NUMBER,
	"INACTIVE_FROM_DATE" TIMESTAMP (6),
	"INACTIVE_TO_DATE" TIMESTAMP (6),
	"GRANT_SOURCE" VARCHAR2(20),
	 CONSTRAINT "AUTH_USER_RESOURCE_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE,
	 CONSTRAINT "AUTH_USER_RESOURCE_UQ" UNIQUE ("USER_ID", "RESOURCE_ID")
  USING INDEX  ENABLE,
	 CONSTRAINT "AUTH_USER_RESOURCE_ST_CK" CHECK (STATUS IN ('ACTIVE', 'REVOKED', 'EXPIRED', 'SUSPENDED')) ENABLE
   ) ;


  CREATE TABLE "AUTH_USER_ROLE"
   (	"ID" NUMBER DEFAULT "SEQ_AUTH_USER_ROLE"."NEXTVAL" NOT NULL ENABLE,
	"USER_ID" NUMBER NOT NULL ENABLE,
	"ROLE_ID" NUMBER NOT NULL ENABLE,
	"GRANTED_BY" VARCHAR2(20),
	"GRANTED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP NOT NULL ENABLE,
	"EXPIRED_AT" TIMESTAMP (6),
	"STATUS" VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL ENABLE,
	 CONSTRAINT "AUTH_USER_ROLE_STATUS_CK" CHECK (STATUS IN ('ACTIVE', 'REVOKED')) ENABLE,
	 CONSTRAINT "AUTH_USER_ROLE_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE,
	 CONSTRAINT "AUTH_USER_ROLE_UQ" UNIQUE ("USER_ID", "ROLE_ID")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "AUTH_USER_SESSION"
   (	"ID" VARCHAR2(64) NOT NULL ENABLE,
	"USER_ID" NUMBER NOT NULL ENABLE,
	"STATUS" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE,
	"ACR_LEVEL" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE,
	"CREATED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP NOT NULL ENABLE,
	"LAST_ACCESS" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP NOT NULL ENABLE,
	"EXPIRES_AT" TIMESTAMP (6) NOT NULL ENABLE,
	"IP_ADDRESS" VARCHAR2(45),
	"USER_AGENT" VARCHAR2(500),
	 CONSTRAINT "CK_USER_SESSION_STATUS" CHECK (STATUS IN (0, 1)) ENABLE,
	 CONSTRAINT "CK_USER_SESSION_ACR" CHECK (ACR_LEVEL IN (0, 1)) ENABLE,
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )
  PARTITION BY RANGE ("EXPIRES_AT") INTERVAL (NUMTOYMINTERVAL(1, 'MONTH'))
 (PARTITION "P_USER_SESSION_INIT"  VALUES LESS THAN (TIMESTAMP' 2025-01-01 00:00:00') )  ENABLE ROW MOVEMENT ;


  CREATE TABLE "AUTH_WARD"
   (	"CODE" NUMBER NOT NULL ENABLE,
	"NAME" VARCHAR2(200) NOT NULL ENABLE,
	"DIVISION_TYPE" VARCHAR2(50) NOT NULL ENABLE,
	"CODENAME" VARCHAR2(200) NOT NULL ENABLE,
	"PROVINCE_CODE" NUMBER NOT NULL ENABLE,
	"STATUS" VARCHAR2(10) DEFAULT 'ACTIVE' NOT NULL ENABLE,
	 CONSTRAINT "CHK_AUTH_WARD_STATUS" CHECK (STATUS IN ('ACTIVE', 'INACTIVE')) ENABLE,
	 CONSTRAINT "PK_AUTH_WARD" PRIMARY KEY ("CODE")
  USING INDEX  ENABLE
   ) ;



-- ------------------------------------------------------------
-- 3. INDEXES
-- ------------------------------------------------------------
CREATE UNIQUE INDEX "AUTH_APPLICATION_PK" ON "AUTH_APPLICATION" ("ID")
  ;


  CREATE UNIQUE INDEX "AUTH_APPLICATION_SERVICE_CODE_UQ" ON "AUTH_APPLICATION" ("SERVICE_CODE")
  ;


  CREATE UNIQUE INDEX "AUTH_APP_PERM_PK" ON "AUTH_APP_PERMISSION" ("ID")
  ;


  CREATE UNIQUE INDEX "AUTH_DEPARTMENT_CODE_UQ" ON "AUTH_DEPARTMENT" ("CODE")
  ;


  CREATE UNIQUE INDEX "AUTH_DEPARTMENT_PK" ON "AUTH_DEPARTMENT" ("ID")
  ;


  CREATE UNIQUE INDEX "AUTH_RESOURCE_PK" ON "AUTH_RESOURCE" ("ID")
  ;


  CREATE UNIQUE INDEX "AUTH_RESOURCE_UQ" ON "AUTH_RESOURCE" ("APP_ID", "RESOURCE_CODE")
  ;


  CREATE UNIQUE INDEX "AUTH_ROLE_CODE_UQ" ON "AUTH_ROLE" ("CODE")
  ;


  CREATE UNIQUE INDEX "AUTH_ROLE_PK" ON "AUTH_ROLE" ("ID")
  ;


  CREATE UNIQUE INDEX "AUTH_USER_EMAIL_UQ" ON "AUTH_USER" ("EMAIL")
  ;


  CREATE UNIQUE INDEX "AUTH_USER_PK" ON "AUTH_USER" ("ID")
  ;


  CREATE UNIQUE INDEX "AUTH_USER_RESOURCE_PK" ON "AUTH_USER_RESOURCE" ("ID")
  ;


  CREATE UNIQUE INDEX "AUTH_USER_RESOURCE_UQ" ON "AUTH_USER_RESOURCE" ("USER_ID", "RESOURCE_ID")
  ;


  CREATE UNIQUE INDEX "AUTH_USER_ROLE_PK" ON "AUTH_USER_ROLE" ("ID")
  ;


  CREATE UNIQUE INDEX "AUTH_USER_ROLE_UQ" ON "AUTH_USER_ROLE" ("USER_ID", "ROLE_ID")
  ;


  CREATE UNIQUE INDEX "AUTH_USER_USERNAME_UQ" ON "AUTH_USER" ("USERNAME")
  ;


  CREATE INDEX "IDX_ART_CLIENT_ID" ON "AUTH_REFRESH_TOKEN" ("CLIENT_ID")
  ;


  CREATE INDEX "IDX_ART_SESSION_ID" ON "AUTH_REFRESH_TOKEN" ("USER_SESSION_ID")
  ;


  CREATE INDEX "IDX_ART_USER_ID" ON "AUTH_REFRESH_TOKEN" ("USER_ID")
  ;


  CREATE INDEX "IDX_AUTH_ADDRESS_USER" ON "AUTH_USER_ADDRESS" ("USER_ID")
  ;


  CREATE INDEX "IDX_AUTH_APP_PERM_APP" ON "AUTH_APP_PERMISSION" ("APP_ID", "STATUS")
  ;


  CREATE INDEX "IDX_AUTH_APP_PERM_USER" ON "AUTH_APP_PERMISSION" ("USER_ID", "STATUS")
  ;


  CREATE INDEX "IDX_AUTH_APP_TYPE" ON "AUTH_APPLICATION" ("APP_TYPE", "STATUS")
  ;


  CREATE INDEX "IDX_AUTH_EXEC_CLIENT_METHOD" ON "AUTH_FLOW_EXECUTION" ("CLIENT_METHOD_ID")
  ;


  CREATE INDEX "IDX_AUTH_EXEC_FLOW_ID" ON "AUTH_FLOW_EXECUTION" ("FLOW_ID")
  ;


  CREATE INDEX "IDX_AUTH_EXEC_PARENT_NODE" ON "AUTH_FLOW_EXECUTION" ("PARENT_NODE_ID")
  ;


  CREATE INDEX "IDX_AUTH_PROFILE_DEPT" ON "AUTH_USER_PROFILE" ("DEPARTMENT_ID")
  ;


  CREATE INDEX "IDX_AUTH_RESOURCE_APP" ON "AUTH_RESOURCE" ("APP_ID", "STATUS")
  ;


  CREATE INDEX "IDX_AUTH_USER_ROLE_USER" ON "AUTH_USER_ROLE" ("USER_ID", "STATUS")
  ;


  CREATE INDEX "IDX_AUTH_USER_STATUS" ON "AUTH_USER" ("STATUS")
  ;


  CREATE INDEX "IDX_AUTH_WARD_PROVINCE" ON "AUTH_WARD" ("PROVINCE_CODE")
  ;


  CREATE INDEX "IDX_CLIENT_SESSION_LOOKUP" ON "AUTH_CLIENT_SESSION" ("USER_SESSION_ID", "APP_ID", "STATUS", "EXPIRES_AT")
   LOCAL
 (PARTITION "P_CLIENT_SESSION_INIT" NOCOMPRESS ) ;


  CREATE INDEX "IDX_SIGNING_KEY_STATUS" ON "AUTH_SIGNING_KEY" ("STATUS")
  ;


  CREATE INDEX "IDX_USER_SESSION_USER_ID" ON "AUTH_USER_SESSION" ("USER_ID", "STATUS", "EXPIRES_AT")
   LOCAL
 (PARTITION "P_USER_SESSION_INIT" NOCOMPRESS ) ;


  CREATE UNIQUE INDEX "PK_AUTH_CLIENT_GROUP" ON "AUTH_CLIENT_GROUP" ("ID")
  ;


  CREATE UNIQUE INDEX "PK_AUTH_DEFAULT_APP_PERM" ON "AUTH_DEFAULT_APP_PERMISSION" ("ID")
  ;


  CREATE UNIQUE INDEX "PK_AUTH_DEFAULT_RESOURCE" ON "AUTH_DEFAULT_RESOURCE" ("ID")
  ;


  CREATE UNIQUE INDEX "PK_AUTH_POSITION" ON "AUTH_POSITION" ("CODE")
  ;


  CREATE UNIQUE INDEX "PK_AUTH_PROVINCE" ON "AUTH_PROVINCE" ("CODE")
  ;


  CREATE UNIQUE INDEX "PK_AUTH_REFRESH_TOKEN" ON "AUTH_REFRESH_TOKEN" ("TOKEN")
  ;


  CREATE UNIQUE INDEX "PK_AUTH_REQUEST_DETAIL" ON "AUTH_REQUEST_DETAIL" ("ID")
  ;


  CREATE UNIQUE INDEX "PK_AUTH_REQUEST_HEADER" ON "AUTH_REQUEST_HEADER" ("ID")
  ;


  CREATE UNIQUE INDEX "PK_AUTH_USER_ADDRESS" ON "AUTH_USER_ADDRESS" ("ID")
  ;


  CREATE UNIQUE INDEX "PK_AUTH_USER_PROFILE" ON "AUTH_USER_PROFILE" ("USER_ID")
  ;


  CREATE UNIQUE INDEX "PK_AUTH_WARD" ON "AUTH_WARD" ("CODE")
  ;


  CREATE UNIQUE INDEX "PK_CLIENT_SESSION" ON "AUTH_CLIENT_SESSION" ("ID")
  ;


  CREATE UNIQUE INDEX "UK_AUTH_CLIENT_GROUP_NAME" ON "AUTH_CLIENT_GROUP" ("NAME")
  ;


  CREATE UNIQUE INDEX "UQ_APP_METHOD" ON "AUTH_CLIENT_METHOD" ("APP_ID", "METHOD_ID")
  ;


  CREATE UNIQUE INDEX "UQ_AUTH_ADDRESS_TYPE" ON "AUTH_USER_ADDRESS" ("USER_ID", "TYPE")
  ;


  CREATE UNIQUE INDEX "UQ_AUTH_CLIENT_ID" ON "AUTH_CLIENT" ("CLIENT_ID")
  ;


  CREATE UNIQUE INDEX "UQ_AUTH_DEFAULT_APP_PERM" ON "AUTH_DEFAULT_APP_PERMISSION" ("ROLE_ID", "POSITION_CODE", "APPLICATION_ID")
  ;


  CREATE UNIQUE INDEX "UQ_AUTH_DEFAULT_RESOURCE" ON "AUTH_DEFAULT_RESOURCE" ("ROLE_ID", "POSITION_CODE", "RESOURCE_ID")
  ;


  CREATE UNIQUE INDEX "UQ_AUTH_FLOW_APP" ON "AUTH_FLOW" ("APP_ID")
  ;


  CREATE UNIQUE INDEX "UQ_AUTH_METHOD" ON "AUTH_METHOD" ("METHOD")
  ;


  CREATE UNIQUE INDEX "UQ_AUTH_PROFILE_EMP_CODE" ON "AUTH_USER_PROFILE" ("EMPLOYEE_CODE")
  ;


  CREATE UNIQUE INDEX "UQ_AUTH_SIGNING_KID" ON "AUTH_SIGNING_KEY" ("KID")
  ;


  CREATE UNIQUE INDEX "UQ_CLIENT_SESSION" ON "AUTH_CLIENT_SESSION" ("USER_SESSION_ID", "APP_ID")
  ;



-- ------------------------------------------------------------
-- 4. PACKAGES (AUTH_PKG, IDENTITY_PKG)
-- ------------------------------------------------------------
CREATE OR REPLACE EDITIONABLE PACKAGE "AUTH_PKG" AS

  PROCEDURE get_flow_by_id(
    p_flow_id NUMBER,
    p_result OUT SYS_REFCURSOR
  );

  PROCEDURE get_client_by_client_id(
    p_client_id VARCHAR2,
    p_result OUT SYS_REFCURSOR
  );

  PROCEDURE get_permission(
    p_user_id NUMBER,
    p_app_id NUMBER,
    p_result OUT SYS_REFCURSOR
  );

  PROCEDURE get_user_info_by_user_id(
    p_user_id NUMBER,
    p_user_profile OUT SYS_REFCURSOR,
    p_user_department OUT SYS_REFCURSOR,
    p_user_address OUT SYS_REFCURSOR,
    p_user_role OUT SYS_REFCURSOR
  );
END AUTH_PKG;
/
CREATE OR REPLACE EDITIONABLE PACKAGE BODY "AUTH_PKG" AS

    PROCEDURE get_flow_by_id(
        p_flow_id NUMBER,
        p_result OUT SYS_REFCURSOR
    ) AS
    BEGIN
        OPEN p_result FOR
            SELECT
                c.id            AS node_id,
                a.id            AS app_id,
                a.acr_level     AS app_level,
                d.id            AS client_method_id,
                e.method        AS method,
                c.requirement   AS requirement,
                c.is_default    AS is_default,
                c.parent_node_id AS parent_node_id,
                f.name          AS theme
            FROM auth_application a
            JOIN auth_flow b
                ON a.id = b.app_id
            JOIN auth_flow_execution c
                ON c.flow_id = b.id
            JOIN auth_client_method d
                ON d.id = c.client_method_id
            JOIN auth_method e
                ON e.id = d.method_id
            JOIN auth_theme f
                ON f.id = a.theme_id
            WHERE b.id = p_flow_id
                AND b.status = 'ACTIVE'
                AND a.status = 'ACTIVE'
                AND c.status = 'ACTIVE'
                AND d.status = 'ACTIVE'
                AND e.status = 1
                AND f.status = 1;
    END get_flow_by_id;

    PROCEDURE get_client_by_client_id(
        p_client_id VARCHAR2,
        p_result OUT SYS_REFCURSOR
    ) AS
    BEGIN
        OPEN p_result FOR
            select
                a.id as id,
                a.client_id as client_id,
                a.client_secret as client_secret,
                a.name as name,
                a.client_type as client_type,
                a.enabled as enabled,
                a.app_id as app_id,
                b.grant_types as grant_types,
                b.redirect_uris as redirect_uris,
                b.allowed_scopes as allowed_scopes,
                b.access_token_ttl as access_token_ttl,
                b.refresh_token_ttl as refresh_token_ttl,
                b.id_token_ttl as id_token_ttl,
                b.token_endpoint_auth as token_endpoint_auth,
                b.require_pkce as require_pkce,
                b.require_consent as require_consent,
                b.post_logout_redirect as post_logout_redirect,
                a.default_url as default_url
            from auth_client a
            join auth_client_oauth b on a.id = b.client_id
        where a.enabled = 1
            and a.client_id = p_client_id;
    END get_client_by_client_id;

    PROCEDURE get_permission(
        p_user_id NUMBER,
        p_app_id NUMBER,
        p_result OUT SYS_REFCURSOR
    ) AS
    BEGIN
        OPEN p_result FOR
            SELECT
                u.id as user_id,
                u.username as username,
                u.display_name as display_name,
                u.mobile as mobile,
                ur.action as user_action,
                r.resource_code as resource_code,
                r.actions as resource_actions,
                r.app_id as app_id,
                role.code as role
            FROM auth_user u
            JOIN auth_user_resource ur
                ON ur.user_id = u.id
            JOIN auth_resource r
                ON r.id = ur.resource_id
            JOIN auth_user_role uro
                ON uro.user_id = u.id
            JOIN auth_role role
                ON role.id = uro.role_id
            WHERE 1 = 1
                AND u.id = p_user_id
                AND ur.status = 'ACTIVE'
                AND r.status = 'ACTIVE'
                AND uro.status = 'ACTIVE'
                AND r.app_id = p_app_id;
    END get_permission;

    PROCEDURE get_user_info_by_user_id(
        p_user_id NUMBER,
        p_user_profile OUT SYS_REFCURSOR,
        p_user_department OUT SYS_REFCURSOR,
        p_user_address OUT SYS_REFCURSOR,
        p_user_role OUT SYS_REFCURSOR
    ) AS
    BEGIN
        OPEN p_user_profile FOR
            SELECT
                u.ID AS user_id,
                u.USERNAME AS username,
                u.EMAIL AS email,
                u.MOBILE AS mobile,
                u.STATUS AS status,

                p.EMPLOYEE_CODE AS employee_code,
                p.FULL_NAME AS full_name,
                p.FIRST_NAME AS first_name,
                p.LAST_NAME AS last_name,
                p.DISPLAY_NAME AS display_name,
                p.GENDER AS gender,
                p.DOB AS dob,
                p.NATIONALITY AS nationality,
                p.ETHNIC AS ethnic,
                p.RELIGION AS religion,
                p.AVATAR_URL AS avatar_url,
                p.CCCD AS cccd,
                p.CCCD_ISSUED_DATE AS cccd_issued_date,
                p.CCCD_ISSUED_PLACE AS cccd_issued_place,
                p.JOIN_DATE AS join_date,
                null     AS leave_date,
                p.POSITION AS position,
                p.DEPARTMENT_ID AS department_id

            FROM AUTH_USER u
            LEFT JOIN AUTH_USER_PROFILE p
                ON p.USER_ID = u.ID
            WHERE u.ID = p_user_id;

        OPEN p_user_department FOR
            SELECT
                d.ID AS department_id,
                d.CODE AS code,
                d.NAME AS name,
                d.PARENT_ID AS parent_id,
                LEVEL AS depth
            FROM AUTH_DEPARTMENT d
            START WITH d.ID = (
                SELECT DEPARTMENT_ID
                FROM AUTH_USER_PROFILE
                WHERE USER_ID = p_user_id
            )
            CONNECT BY PRIOR d.PARENT_ID = d.ID
                   AND LEVEL <= 5
            ORDER BY LEVEL;

        OPEN p_user_address FOR
            SELECT
                a.TYPE AS type,
                a.PROVINCE_CODE AS province_code,
                p.NAME AS province_name,
                a.WARD_CODE AS ward_code,
                w.NAME AS ward_name,
                a.DETAIL AS detail
            FROM AUTH_USER_ADDRESS a
            LEFT JOIN AUTH_PROVINCE p
                ON p.CODE = a.PROVINCE_CODE
            LEFT JOIN AUTH_WARD w
                ON w.CODE = a.WARD_CODE
            WHERE a.USER_ID = p_user_id;

        OPEN p_user_role FOR
            SELECT
                r.ID AS role_id,
                r.CODE AS code,
                r.NAME AS name,
                r.DESCRIPTION AS description,
                ur.GRANTED_AT AS granted_at,
                ur.EXPIRED_AT AS expired_at
            FROM AUTH_USER_ROLE ur
            JOIN AUTH_ROLE r
                ON r.ID = ur.ROLE_ID
            WHERE ur.USER_ID = p_user_id
              AND ur.STATUS = 'ACTIVE'
              AND (ur.EXPIRED_AT IS NULL OR ur.EXPIRED_AT > CURRENT_TIMESTAMP);
    END get_user_info_by_user_id;

END AUTH_PKG;
/


  CREATE OR REPLACE EDITIONABLE PACKAGE "IDENTITY_PKG" AS

    PROCEDURE GET_USER_INFOR_BY_USER_ID(
        p_user_id       IN  NUMBER,
        p_employee_code IN  VARCHAR2,
        p_user_info     OUT SYS_REFCURSOR
    );
    PROCEDURE get_resources (
        p_app_id         IN AUTH_APPLICATION.ID%TYPE,
        p_resource_id    IN AUTH_RESOURCE.ID%TYPE,
        p_resource_code  IN AUTH_RESOURCE.RESOURCE_CODE%TYPE,
        p_service_code   IN AUTH_APPLICATION.SERVICE_CODE%TYPE,
        p_cursor         OUT SYS_REFCURSOR
    );


END IDENTITY_PKG;
/
CREATE OR REPLACE EDITIONABLE PACKAGE BODY "IDENTITY_PKG" AS

    PROCEDURE GET_USER_INFOR_BY_USER_ID(
        p_user_id       IN  NUMBER,
        p_employee_code IN  VARCHAR2,
        p_user_info     OUT SYS_REFCURSOR
    ) AS
    BEGIN
        OPEN p_user_info FOR
            SELECT
                u.ID                 AS USER_ID,
                up.EMPLOYEE_CODE     AS EMPLOYEE_CODE,
                u.USERNAME           AS USERNAME,
                u.EMAIL              AS EMAIL,
                up.EMAIL_PERSONAL    AS EMAIL_PERSONAL,
                u.MOBILE             AS MOBILE,
                pos.CODE             AS POSITION_CODE,
                pos.NAME             AS POSITION,
                u.STATUS             AS STATUS,
                up.FIRST_NAME        AS FIRST_NAME,
                up.LAST_NAME         AS LAST_NAME,
                up.FULL_NAME         AS FULL_NAME,
                up.DISPLAY_NAME      AS DISPLAY_NAME,
                up.GENDER            AS GENDER,
                up.DOB               AS DOB,
                up.NATIONALITY       AS NATIONALITY,
                up.ETHNIC            AS ETHNIC,
                up.RELIGION          AS RELIGION,
                up.AVATAR_URL        AS AVATAR_URL,
                up.CCCD              AS NUMBER_ID,
                up.CCCD_ISSUED_DATE  AS NUMBER_ID_ISSUED_DATE,
                up.CCCD_ISSUED_PLACE AS NUMBER_ID_ISSUED_PLACE,
                up.JOIN_DATE         AS JOIN_DATE,
                up.DEPARTMENT_ID     AS DEPARTMENT_ID
            FROM AUTH_USER u
            JOIN AUTH_USER_PROFILE up  ON up.USER_ID = u.ID
            LEFT JOIN AUTH_POSITION     pos ON pos.CODE   = up.POSITION
            WHERE (p_user_id is null OR u.ID = p_user_id)
              AND (p_employee_code is null OR up.EMPLOYEE_CODE = p_employee_code);
    END GET_USER_INFOR_BY_USER_ID;

    PROCEDURE get_resources (
        p_app_id         IN AUTH_APPLICATION.ID%TYPE,
        p_resource_id    IN AUTH_RESOURCE.ID%TYPE,
        p_resource_code  IN AUTH_RESOURCE.RESOURCE_CODE%TYPE,
        p_service_code   IN AUTH_APPLICATION.SERVICE_CODE%TYPE,
        p_cursor         OUT SYS_REFCURSOR
    ) AS
        v_sql   CLOB := '
            SELECT
                r.ID                AS resource_id,
                a.ID                AS app_id,

                r.RESOURCE_CODE     AS resource_code,
                r.RESOURCE_NAME     AS resource_name,
                r.RESOURCE_TYPE     AS resource_type,
                r.ACTIONS           AS actions,
                r.LDAP_GROUP_NAME   AS ldap_group_name,
                r.DESCRIPTION       AS description,
                r.STATUS            AS resource_status,

                a.NAME              AS app_name,
                a.APP_TYPE          AS app_type,
                a.SERVICE_CODE      AS service_code,
                a.STATUS            AS app_status

            FROM AUTH_RESOURCE r
            JOIN AUTH_APPLICATION a
                ON a.ID = r.APP_ID
            WHERE 1 = 1
        ';

        v_cursor   INTEGER;
        v_refcursor SYS_REFCURSOR;
    BEGIN
        -- build SQL
        IF p_resource_id IS NOT NULL THEN
            v_sql := v_sql || ' AND r.ID = :resource_id';
        END IF;

        IF p_app_id IS NOT NULL THEN
            v_sql := v_sql || ' AND a.ID = :app_id';
        END IF;

        IF p_resource_code IS NOT NULL THEN
            v_sql := v_sql || ' AND r.RESOURCE_CODE = :resource_code';
        END IF;

        IF p_service_code IS NOT NULL THEN
            v_sql := v_sql || ' AND a.SERVICE_CODE = :service_code';
        END IF;

        -- parse
        v_cursor := DBMS_SQL.OPEN_CURSOR;
        DBMS_SQL.PARSE(v_cursor, v_sql, DBMS_SQL.NATIVE);

        -- bind động
        IF p_resource_id IS NOT NULL THEN
            DBMS_SQL.BIND_VARIABLE(v_cursor, ':resource_id', p_resource_id);
        END IF;

        IF p_app_id IS NOT NULL THEN
            DBMS_SQL.BIND_VARIABLE(v_cursor, ':app_id', p_app_id);
        END IF;

        IF p_resource_code IS NOT NULL THEN
            DBMS_SQL.BIND_VARIABLE(v_cursor, ':resource_code', p_resource_code);
        END IF;

        IF p_service_code IS NOT NULL THEN
            DBMS_SQL.BIND_VARIABLE(v_cursor, ':service_code', p_service_code);
        END IF;

        -- convert sang refcursor
        v_refcursor := DBMS_SQL.TO_REFCURSOR(v_cursor);

        p_cursor := v_refcursor;
    END get_resources;


END IDENTITY_PKG;
/


  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "AUTH_PKG" AS

    PROCEDURE get_flow_by_id(
        p_flow_id NUMBER,
        p_result OUT SYS_REFCURSOR
    ) AS
    BEGIN
        OPEN p_result FOR
            SELECT
                c.id            AS node_id,
                a.id            AS app_id,
                a.acr_level     AS app_level,
                d.id            AS client_method_id,
                e.method        AS method,
                c.requirement   AS requirement,
                c.is_default    AS is_default,
                c.parent_node_id AS parent_node_id,
                f.name          AS theme
            FROM auth_application a
            JOIN auth_flow b
                ON a.id = b.app_id
            JOIN auth_flow_execution c
                ON c.flow_id = b.id
            JOIN auth_client_method d
                ON d.id = c.client_method_id
            JOIN auth_method e
                ON e.id = d.method_id
            JOIN auth_theme f
                ON f.id = a.theme_id
            WHERE b.id = p_flow_id
                AND b.status = 'ACTIVE'
                AND a.status = 'ACTIVE'
                AND c.status = 'ACTIVE'
                AND d.status = 'ACTIVE'
                AND e.status = 1
                AND f.status = 1;
    END get_flow_by_id;

    PROCEDURE get_client_by_client_id(
        p_client_id VARCHAR2,
        p_result OUT SYS_REFCURSOR
    ) AS
    BEGIN
        OPEN p_result FOR
            select
                a.id as id,
                a.client_id as client_id,
                a.client_secret as client_secret,
                a.name as name,
                a.client_type as client_type,
                a.enabled as enabled,
                a.app_id as app_id,
                b.grant_types as grant_types,
                b.redirect_uris as redirect_uris,
                b.allowed_scopes as allowed_scopes,
                b.access_token_ttl as access_token_ttl,
                b.refresh_token_ttl as refresh_token_ttl,
                b.id_token_ttl as id_token_ttl,
                b.token_endpoint_auth as token_endpoint_auth,
                b.require_pkce as require_pkce,
                b.require_consent as require_consent,
                b.post_logout_redirect as post_logout_redirect,
                a.default_url as default_url
            from auth_client a
            join auth_client_oauth b on a.id = b.client_id
        where a.enabled = 1
            and a.client_id = p_client_id;
    END get_client_by_client_id;

    PROCEDURE get_permission(
        p_user_id NUMBER,
        p_app_id NUMBER,
        p_result OUT SYS_REFCURSOR
    ) AS
    BEGIN
        OPEN p_result FOR
            SELECT
                u.id as user_id,
                u.username as username,
                u.display_name as display_name,
                u.mobile as mobile,
                ur.action as user_action,
                r.resource_code as resource_code,
                r.actions as resource_actions,
                r.app_id as app_id,
                role.code as role
            FROM auth_user u
            JOIN auth_user_resource ur
                ON ur.user_id = u.id
            JOIN auth_resource r
                ON r.id = ur.resource_id
            JOIN auth_user_role uro
                ON uro.user_id = u.id
            JOIN auth_role role
                ON role.id = uro.role_id
            WHERE 1 = 1
                AND u.id = p_user_id
                AND ur.status = 'ACTIVE'
                AND r.status = 'ACTIVE'
                AND uro.status = 'ACTIVE'
                AND r.app_id = p_app_id;
    END get_permission;

    PROCEDURE get_user_info_by_user_id(
        p_user_id NUMBER,
        p_user_profile OUT SYS_REFCURSOR,
        p_user_department OUT SYS_REFCURSOR,
        p_user_address OUT SYS_REFCURSOR,
        p_user_role OUT SYS_REFCURSOR
    ) AS
    BEGIN
        OPEN p_user_profile FOR
            SELECT
                u.ID AS user_id,
                u.USERNAME AS username,
                u.EMAIL AS email,
                u.MOBILE AS mobile,
                u.STATUS AS status,

                p.EMPLOYEE_CODE AS employee_code,
                p.FULL_NAME AS full_name,
                p.FIRST_NAME AS first_name,
                p.LAST_NAME AS last_name,
                p.DISPLAY_NAME AS display_name,
                p.GENDER AS gender,
                p.DOB AS dob,
                p.NATIONALITY AS nationality,
                p.ETHNIC AS ethnic,
                p.RELIGION AS religion,
                p.AVATAR_URL AS avatar_url,
                p.CCCD AS cccd,
                p.CCCD_ISSUED_DATE AS cccd_issued_date,
                p.CCCD_ISSUED_PLACE AS cccd_issued_place,
                p.JOIN_DATE AS join_date,
                null     AS leave_date,
                p.POSITION AS position,
                p.DEPARTMENT_ID AS department_id

            FROM AUTH_USER u
            LEFT JOIN AUTH_USER_PROFILE p
                ON p.USER_ID = u.ID
            WHERE u.ID = p_user_id;

        OPEN p_user_department FOR
            SELECT
                d.ID AS department_id,
                d.CODE AS code,
                d.NAME AS name,
                d.PARENT_ID AS parent_id,
                LEVEL AS depth
            FROM AUTH_DEPARTMENT d
            START WITH d.ID = (
                SELECT DEPARTMENT_ID
                FROM AUTH_USER_PROFILE
                WHERE USER_ID = p_user_id
            )
            CONNECT BY PRIOR d.PARENT_ID = d.ID
                   AND LEVEL <= 5
            ORDER BY LEVEL;

        OPEN p_user_address FOR
            SELECT
                a.TYPE AS type,
                a.PROVINCE_CODE AS province_code,
                p.NAME AS province_name,
                a.WARD_CODE AS ward_code,
                w.NAME AS ward_name,
                a.DETAIL AS detail
            FROM AUTH_USER_ADDRESS a
            LEFT JOIN AUTH_PROVINCE p
                ON p.CODE = a.PROVINCE_CODE
            LEFT JOIN AUTH_WARD w
                ON w.CODE = a.WARD_CODE
            WHERE a.USER_ID = p_user_id;

        OPEN p_user_role FOR
            SELECT
                r.ID AS role_id,
                r.CODE AS code,
                r.NAME AS name,
                r.DESCRIPTION AS description,
                ur.GRANTED_AT AS granted_at,
                ur.EXPIRED_AT AS expired_at
            FROM AUTH_USER_ROLE ur
            JOIN AUTH_ROLE r
                ON r.ID = ur.ROLE_ID
            WHERE ur.USER_ID = p_user_id
              AND ur.STATUS = 'ACTIVE'
              AND (ur.EXPIRED_AT IS NULL OR ur.EXPIRED_AT > CURRENT_TIMESTAMP);
    END get_user_info_by_user_id;

END AUTH_PKG;
/


  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "IDENTITY_PKG" AS

    PROCEDURE GET_USER_INFOR_BY_USER_ID(
        p_user_id       IN  NUMBER,
        p_employee_code IN  VARCHAR2,
        p_user_info     OUT SYS_REFCURSOR
    ) AS
    BEGIN
        OPEN p_user_info FOR
            SELECT
                u.ID                 AS USER_ID,
                up.EMPLOYEE_CODE     AS EMPLOYEE_CODE,
                u.USERNAME           AS USERNAME,
                u.EMAIL              AS EMAIL,
                up.EMAIL_PERSONAL    AS EMAIL_PERSONAL,
                u.MOBILE             AS MOBILE,
                pos.CODE             AS POSITION_CODE,
                pos.NAME             AS POSITION,
                u.STATUS             AS STATUS,
                up.FIRST_NAME        AS FIRST_NAME,
                up.LAST_NAME         AS LAST_NAME,
                up.FULL_NAME         AS FULL_NAME,
                up.DISPLAY_NAME      AS DISPLAY_NAME,
                up.GENDER            AS GENDER,
                up.DOB               AS DOB,
                up.NATIONALITY       AS NATIONALITY,
                up.ETHNIC            AS ETHNIC,
                up.RELIGION          AS RELIGION,
                up.AVATAR_URL        AS AVATAR_URL,
                up.CCCD              AS NUMBER_ID,
                up.CCCD_ISSUED_DATE  AS NUMBER_ID_ISSUED_DATE,
                up.CCCD_ISSUED_PLACE AS NUMBER_ID_ISSUED_PLACE,
                up.JOIN_DATE         AS JOIN_DATE,
                up.DEPARTMENT_ID     AS DEPARTMENT_ID
            FROM AUTH_USER u
            JOIN AUTH_USER_PROFILE up  ON up.USER_ID = u.ID
            LEFT JOIN AUTH_POSITION     pos ON pos.CODE   = up.POSITION
            WHERE (p_user_id is null OR u.ID = p_user_id)
              AND (p_employee_code is null OR up.EMPLOYEE_CODE = p_employee_code);
    END GET_USER_INFOR_BY_USER_ID;

    PROCEDURE get_resources (
        p_app_id         IN AUTH_APPLICATION.ID%TYPE,
        p_resource_id    IN AUTH_RESOURCE.ID%TYPE,
        p_resource_code  IN AUTH_RESOURCE.RESOURCE_CODE%TYPE,
        p_service_code   IN AUTH_APPLICATION.SERVICE_CODE%TYPE,
        p_cursor         OUT SYS_REFCURSOR
    ) AS
        v_sql   CLOB := '
            SELECT
                r.ID                AS resource_id,
                a.ID                AS app_id,

                r.RESOURCE_CODE     AS resource_code,
                r.RESOURCE_NAME     AS resource_name,
                r.RESOURCE_TYPE     AS resource_type,
                r.ACTIONS           AS actions,
                r.LDAP_GROUP_NAME   AS ldap_group_name,
                r.DESCRIPTION       AS description,
                r.STATUS            AS resource_status,

                a.NAME              AS app_name,
                a.APP_TYPE          AS app_type,
                a.SERVICE_CODE      AS service_code,
                a.STATUS            AS app_status

            FROM AUTH_RESOURCE r
            JOIN AUTH_APPLICATION a
                ON a.ID = r.APP_ID
            WHERE 1 = 1
        ';

        v_cursor   INTEGER;
        v_refcursor SYS_REFCURSOR;
    BEGIN
        -- build SQL
        IF p_resource_id IS NOT NULL THEN
            v_sql := v_sql || ' AND r.ID = :resource_id';
        END IF;

        IF p_app_id IS NOT NULL THEN
            v_sql := v_sql || ' AND a.ID = :app_id';
        END IF;

        IF p_resource_code IS NOT NULL THEN
            v_sql := v_sql || ' AND r.RESOURCE_CODE = :resource_code';
        END IF;

        IF p_service_code IS NOT NULL THEN
            v_sql := v_sql || ' AND a.SERVICE_CODE = :service_code';
        END IF;

        -- parse
        v_cursor := DBMS_SQL.OPEN_CURSOR;
        DBMS_SQL.PARSE(v_cursor, v_sql, DBMS_SQL.NATIVE);

        -- bind động
        IF p_resource_id IS NOT NULL THEN
            DBMS_SQL.BIND_VARIABLE(v_cursor, ':resource_id', p_resource_id);
        END IF;

        IF p_app_id IS NOT NULL THEN
            DBMS_SQL.BIND_VARIABLE(v_cursor, ':app_id', p_app_id);
        END IF;

        IF p_resource_code IS NOT NULL THEN
            DBMS_SQL.BIND_VARIABLE(v_cursor, ':resource_code', p_resource_code);
        END IF;

        IF p_service_code IS NOT NULL THEN
            DBMS_SQL.BIND_VARIABLE(v_cursor, ':service_code', p_service_code);
        END IF;

        -- convert sang refcursor
        v_refcursor := DBMS_SQL.TO_REFCURSOR(v_cursor);

        p_cursor := v_refcursor;
    END get_resources;


END IDENTITY_PKG;
/


  

-- =============================================================================
-- SCHEMA: change_user1
-- =============================================================================
CONNECT change_user1/"change@123456"@localhost:1521/AUTHPDB1

-- ------------------------------------------------------------
-- 1. SEQUENCES
-- ------------------------------------------------------------
CREATE SEQUENCE  "SEQ_CHG_APPROVER"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 9 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;


   CREATE SEQUENCE  "SEQ_CHG_AUDIT_LOG"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 22 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;


   CREATE SEQUENCE  "SEQ_CHG_CHANGE_REQUEST"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 10 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;


   CREATE SEQUENCE  "SEQ_CHG_CHECKLIST_ITEM"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 16 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;


   CREATE SEQUENCE  "SEQ_CHG_DOCUMENT"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;


   CREATE SEQUENCE  "SEQ_CHG_GOLIVE_JOB"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 12 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;


   CREATE SEQUENCE  "SEQ_CHG_TEAM_MEMBER"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 22 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;


  

-- ------------------------------------------------------------
-- 2. TABLES
-- ------------------------------------------------------------

  CREATE TABLE "CHG_APPROVER"
   (	"ID" NUMBER DEFAULT "SEQ_CHG_APPROVER"."NEXTVAL",
	"CHANGE_REQUEST_ID" NUMBER NOT NULL ENABLE,
	"USER_ID" VARCHAR2(50),
	"USERNAME" VARCHAR2(100),
	"FULL_NAME" VARCHAR2(200),
	"EMPLOYEE_CODE" VARCHAR2(50),
	"APPROVE_STATUS" VARCHAR2(20) DEFAULT 'PENDING',
	"NOTE" VARCHAR2(1000),
	"DECIDED_AT" TIMESTAMP (6),
	"STATUS" NUMBER(1,0) DEFAULT 1,
	"CREATED_BY" VARCHAR2(100),
	"CREATED_BY_CODE" VARCHAR2(50),
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP,
	"UPDATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP,
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "CHG_AUDIT_LOG"
   (	"ID" NUMBER DEFAULT "SEQ_CHG_AUDIT_LOG"."NEXTVAL",
	"CHANGE_REQUEST_ID" NUMBER NOT NULL ENABLE,
	"ACTION" VARCHAR2(50),
	"FROM_STATUS" VARCHAR2(20),
	"TO_STATUS" VARCHAR2(20),
	"PERFORMED_BY" VARCHAR2(100),
	"PERFORMED_BY_CODE" VARCHAR2(50),
	"NOTE" VARCHAR2(1000),
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP,
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "CHG_CHANGE_REQUEST"
   (	"ID" NUMBER DEFAULT "SEQ_CHG_CHANGE_REQUEST"."NEXTVAL",
	"CHANGE_ID" VARCHAR2(36) NOT NULL ENABLE,
	"CHANGE_NAME" VARCHAR2(200) NOT NULL ENABLE,
	"CONTENT" CLOB,
	"GIT_LINK" VARCHAR2(500),
	"STATUS" VARCHAR2(20) NOT NULL ENABLE,
	"GOLIVE_AT" TIMESTAMP (6),
	"CREATED_BY" VARCHAR2(100),
	"CREATED_BY_CODE" VARCHAR2(50),
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP,
	"UPDATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP,
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "CHG_CHECKLIST_ITEM"
   (	"ID" NUMBER DEFAULT "SEQ_CHG_CHECKLIST_ITEM"."NEXTVAL",
	"CHANGE_REQUEST_ID" NUMBER NOT NULL ENABLE,
	"PHASE" VARCHAR2(20),
	"STEP_TEXT" VARCHAR2(1000),
	"ORDER_NUM" NUMBER,
	"ASSIGNED_TO" VARCHAR2(100),
	"ASSIGNED_TO_CODE" VARCHAR2(50),
	"STATUS" NUMBER(1,0) DEFAULT 1,
	"CREATED_BY" VARCHAR2(100),
	"CREATED_BY_CODE" VARCHAR2(50),
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP,
	"UPDATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP,
	"TASK_STATUS" VARCHAR2(20) DEFAULT 'READY',
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "CHG_DOCUMENT"
   (	"ID" NUMBER DEFAULT "SEQ_CHG_DOCUMENT"."NEXTVAL",
	"CHANGE_REQUEST_ID" NUMBER NOT NULL ENABLE,
	"DOC_TYPE" VARCHAR2(20) NOT NULL ENABLE,
	"TITLE" VARCHAR2(200) NOT NULL ENABLE,
	"URL" VARCHAR2(1000),
	"NOTE" VARCHAR2(500),
	"STATUS" NUMBER(1,0) DEFAULT 1,
	"CREATED_BY" VARCHAR2(100),
	"CREATED_BY_CODE" VARCHAR2(50),
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP,
	"UPDATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP,
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "CHG_GOLIVE_JOB"
   (	"ID" NUMBER DEFAULT "SEQ_CHG_GOLIVE_JOB"."NEXTVAL",
	"CHANGE_REQUEST_ID" NUMBER NOT NULL ENABLE,
	"NAME" VARCHAR2(200),
	"LINK" VARCHAR2(500),
	"JOB_TYPE" VARCHAR2(50),
	"ORDER_NUM" NUMBER,
	"STATUS" NUMBER(1,0) DEFAULT 1,
	"CREATED_BY" VARCHAR2(100),
	"CREATED_BY_CODE" VARCHAR2(50),
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP,
	"UPDATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP,
	"JOB_STATUS" VARCHAR2(20) DEFAULT 'PENDING',
	"STARTED_AT" TIMESTAMP (6),
	"COMPLETED_AT" TIMESTAMP (6),
	"RESULT_NOTE" VARCHAR2(500),
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "CHG_TEAM_MEMBER"
   (	"ID" NUMBER DEFAULT "SEQ_CHG_TEAM_MEMBER"."NEXTVAL",
	"CHANGE_REQUEST_ID" NUMBER NOT NULL ENABLE,
	"USER_ID" VARCHAR2(50),
	"USERNAME" VARCHAR2(100),
	"FULL_NAME" VARCHAR2(200),
	"EMPLOYEE_CODE" VARCHAR2(50),
	"MEMBER_ROLE" VARCHAR2(20),
	"IS_LEAD" NUMBER(1,0) DEFAULT 0,
	"STATUS" NUMBER(1,0) DEFAULT 1,
	"CREATED_BY" VARCHAR2(100),
	"CREATED_BY_CODE" VARCHAR2(50),
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP,
	"UPDATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP,
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;


   

-- ------------------------------------------------------------
-- 3. INDEXES
-- ------------------------------------------------------------
CREATE UNIQUE INDEX "UQ_CHG_REQ_CHANGE_ID" ON "CHG_CHANGE_REQUEST" ("CHANGE_ID")
  ;



EXIT;